### ISSUE TITLE
Unexpected Subfolders in Scraped Data Causing Naming Conflicts

### ISSUE THREAD

**Issue by avinashladdha** [epiverse-connect/epiverse-search#22]
**Description**:
I'm encountering an issue where scraped data is being stored in a folder structure that includes unexpected subfolders. This is causing problems when trying to access and process the data, as the folder and file names are being used to assign values to other parameters.

Example:
**Expected Structure**: package_name/man/test_file.md
**Erroneous Structure:** package_name/man/macros/test_file.md

**Comment by Bisaloo** [comment]
Thanks for flagging!

I suspect we may want to discard some of these folders. Here is how I would go about this issue:

1. List of possible subfolders
2. Post the list in this issue
3. Decide whether each subfolder should be discarded or moved one level up.

In particular, at this time, I suspect we will likely want to discard `macros`, `figures`.

**Comment by chartgerink** [comment]
In response to @bisaloo's post, I checked what I have available in the download on my machine:


- ./sources/pomp/man/macros
- ./sources/epiR/man/figures
- ./sources/covid19sf/man/figures
- ./sources/linelist/man/figures
- ./sources/surveillance/man/macros
- ./sources/covid19italy/man/figures
- ./sources/covid19.analytics/man/figures
- ./sources/covid19.analytics/vignettes/man/figures
- ./sources/cfr/man/figures
- ./sources/coronavirus/man/figures
- ./sources/finalsize/man/figures
- ./sources/EpiNow2/man/figures
- ./sources/cleanepi/man/figures
- ./sources/contactdata/man/figures
- ./sources/SimInf/man/macros
- ./sources/SimInf/man/examples

So the unique ones are `figures`, `macros`, and `examples` from what I can see. For each of these, discard or move one level up?

**Comment by Bisaloo** [comment]
`examples` should be ideally be included in the file before being converted to markdown. Could you double check if it's the case please?

Otherwise, I would likely drop all the subfolders.

**Comment by chartgerink** [comment]
Can confirm in the case of `SimInf` that it is indeed included in the markdown file, and dropping the `examples` subfolder is of no risk 👍 Shall I move ahead and remove all the subfolders in `man/`? 😊

**Comment by Bisaloo** [comment]
Yes, sounds reasonable to me to remove subfolders.

**Comment by Bisaloo** [comment]
Fixed by #25
