### ISSUE TITLE
Search results are assumed to be sorted by front-end

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-search#36]
Currently, the search front-end takes results as ordered in the json file. This means that if the backend didn't previously sort them by score, the displayed top results might not actually be the best matches.

Is this what we want?

Should the front-end sort the results or assume they have been sorted already by the back-end? In all cases, this should be documented in `api-design.md`.

cc @chartgerink

**Comment by chartgerink** [comment]
My initial response would be that the front-end should not assume sorting if not part of the spec. 

I do think it makes sense to include it in the spec, but also happy to sort on the front-end.
