### ISSUE TITLE
Develop front-end

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-search#6]
This includes the user interface & the code to interact with the backend (#3)

**Comment by chartgerink** [comment]
[Initial version is live](https://epiverse-connect.github.io/epiverse-search-frontend/) and continues to be developed over in `epiverse-search-frontend`](https://github.com/epiverse-connect/epiverse-search-frontend).

Would we consider this item resolved, even if the development of the frontend will continue?
