### ISSUE TITLE
Investigate limitations and lessons learned from previous work

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-connect/epiverse-search#9]
Related work:

- https://github.com/r-hub/pkgsearch/
- https://github.com/epiverse-trace/llm-guidance

**Comment by Bisaloo** [comment]
I asked Adam for his advice and feedback and he confirmed he was using the approach suggested in https://github.com/epiverse-connect/epiverse-search/issues/4#issuecomment-2133422997 and it was giving satisfactory results for the most part.

The main weakness was to answer very short queries, which didn't have enough content & context to position the point in a sensible manner in the embedding space.

**Comment by chartgerink** [comment]
Thanks for this great input @Bisaloo! 

If I may add to the `pkgsearch` option: they also provide an open API that already does a lot of heavy lifting. We can build our scrapers on top of this. The only downside is that the API is not well documented, as far as i can find. I was able to figure out the API path for one package:

`https://crandb.r-pkg.org/<package>` 

For the `llm-guidance` option, this is a great conceptual example. Adding to the limitations, I would propose that the Shiny app merges a lot of front-end and back-end operations in one place, and requires server side operations in one place - in other words: it is not modular.
